export const CALCULATOR_PARAMETER_DOCS = {
  fulfillment_mode: {
    label: 'Схема',
    unit: '',
    section: 'Базовые параметры',
    role: 'formula',
    tooltip: 'Выбирает активный канал расходов. FBO использует логистику, хранение и прочие расходы FBO; FBS использует последнюю милю, операции продавца, хранение и прочие расходы FBS.',
    formula: 'channelVar = FBO fields или FBS fields',
  },
  package_mode: {
    label: 'Упаковка',
    unit: '',
    section: 'Базовые параметры',
    role: 'logistics',
    tooltip: 'Определяет режим расчета тарифов: box берет коробочный тариф, pallet берет паллетный тариф и при необходимости распределяет его на коробки паллеты.',
    formula: 'tariff = tariffs[fulfillmentMode][package_mode]',
  },
  price: {
    label: 'Цена продажи',
    unit: 'руб',
    section: 'Базовые параметры',
    role: 'formula',
    tooltip: 'Фактическая цена продажи после скидок. Это база для комиссии WB, эквайринга, промо, налога, маржинальности и contribution.',
    formula: 'priceNet = price',
  },
  wb_cabinet_price: {
    label: 'Цена кабинет WB',
    unit: 'руб',
    section: 'Базовые параметры',
    role: 'reference',
    tooltip: 'Справочная цена из кабинета или истории цен WB. В расчет unit-экономики не входит, чтобы не дублировать цену продажи.',
    formula: 'Справочно, без влияния на calculate()',
  },
  monthly_plan: {
    label: 'План / мес.',
    unit: 'шт',
    section: 'Базовые параметры',
    role: 'view',
    tooltip: 'План продаж в месяц. Используется для прогноза месячной прибыли: contribution на единицу умножается на план и уменьшается на постоянные расходы.',
    formula: 'monthlyProfit = contribution * monthly_plan - fixedMonthlyTotal',
  },
  size_length_cm: {
    label: 'Длина',
    unit: 'см',
    section: 'Габариты',
    role: 'logistics',
    tooltip: 'Длина товара или короба. Вместе с шириной и высотой дает объем в литрах и влияет на расчет логистики по объемному весу.',
    formula: 'volumeLiters = L * W * H / 1000',
  },
  size_width_cm: {
    label: 'Ширина',
    unit: 'см',
    section: 'Габариты',
    role: 'logistics',
    tooltip: 'Ширина товара или короба. Участвует в объеме, признаке КГТ и расчете вместимости на паллете.',
    formula: 'volumeLiters = L * W * H / 1000',
  },
  size_height_cm: {
    label: 'Высота',
    unit: 'см',
    section: 'Габариты',
    role: 'logistics',
    tooltip: 'Высота товара или короба. Участвует в объеме, признаке КГТ и расчете количества коробов по высоте паллеты.',
    formula: 'volumeLiters = L * W * H / 1000',
  },
  weight_kg: {
    label: 'Вес кг',
    unit: 'кг',
    section: 'Габариты',
    role: 'logistics',
    tooltip: 'Фактический вес. Для весовых тарифов сравнивается с объемным весом; для литровых тарифов WB используется объем товара.',
    formula: 'billableWeightKg = max(weight_kg, volumeLiters / 5)',
  },
  wb_boxes_per_pallet: {
    label: 'Коробов на паллете',
    unit: 'шт',
    section: 'Габариты',
    role: 'logistics',
    tooltip: 'Ручное количество коробов на паллете. Если оставить 0, калькулятор рассчитает вместимость автоматически по габаритам короба.',
    formula: 'manual > 0 ? manual : calculatedPalletCapacity',
  },
  logistics_direction: {
    label: 'Направление логистики',
    unit: '',
    section: 'Логистика',
    role: 'logistics',
    tooltip: 'Направление или склад из справочника WB. При выборе подтягиваются тарифы для активных FBO/FBS и box/pallet и пересчитываются логистика и хранение.',
    formula: 'calculateLogisticsCost(product, fulfillmentMode, direction)',
  },
  pickup_point: {
    label: 'ПВЗ',
    unit: '',
    section: 'Логистика',
    role: 'logistics',
    tooltip: 'Выбранный ПВЗ из справочника. Его directionId используется как направление логистики и обновляет тарифы активной схемы.',
    formula: 'pickup_point -> logistics_direction',
  },
  cogs_purchase: {
    label: 'Закупочная цена',
    unit: 'руб',
    section: 'Себестоимость',
    role: 'formula',
    tooltip: 'Закупка одной единицы товара. Входит в базовую себестоимость до учета брака.',
    formula: 'cogsBase += cogs_purchase',
  },
  cogs_packaging: {
    label: 'Упаковка',
    unit: 'руб',
    section: 'Себестоимость',
    role: 'formula',
    tooltip: 'Стоимость упаковки одной единицы. Складывается с закупкой, сборкой и доставкой до WB.',
    formula: 'cogsBase += cogs_packaging',
  },
  cogs_fulfillment: {
    label: 'Фулфилмент / сборка',
    unit: 'руб',
    section: 'Себестоимость',
    role: 'formula',
    tooltip: 'Сборка, маркировка, подготовка или услуги фулфилмента на одну единицу до передачи в канал продаж.',
    formula: 'cogsBase += cogs_fulfillment',
  },
  cogs_inbound_to_wb: {
    label: 'Доставка до WB',
    unit: 'руб',
    section: 'Себестоимость',
    role: 'formula',
    tooltip: 'Доставка одной единицы до склада или точки передачи WB. Это часть себестоимости, а не логистика WB после продажи.',
    formula: 'cogsBase += cogs_inbound_to_wb',
  },
  waste_pct: {
    label: 'Брак',
    unit: '%',
    section: 'Себестоимость',
    role: 'formula',
    tooltip: 'Процент брака или потерь партии. Увеличивает базовую себестоимость: cogsBase умножается на 1 + процент брака.',
    formula: 'cogsWithWaste = cogsBase * (1 + waste_pct / 100)',
  },
  fbo_wb_logistics: {
    label: 'Логистика WB FBO',
    unit: 'руб',
    section: 'Логистика',
    role: 'formula',
    tooltip: 'Логистика WB на одну продажу для FBO. Может считаться по весовому тарифу base/per_kg или по литровой формуле WB из справочника.',
    formula: 'box: boxDeliveryBase + boxDeliveryLiter * max(volumeLiters - 1, 0)',
  },
  fbo_storage: {
    label: 'Хранение FBO',
    unit: 'руб',
    section: 'Логистика',
    role: 'formula',
    tooltip: 'Хранение на единицу для FBO. Для коробочного тарифа может считаться как база хранения плюс доплата за литры сверх первого.',
    formula: 'boxStorageBase + boxStorageLiter * max(volumeLiters - 1, 0)',
  },
  fbo_other: {
    label: 'Прочее FBO',
    unit: 'руб',
    section: 'Логистика',
    role: 'formula',
    tooltip: 'Прочие переменные расходы WB или канала на единицу для FBO. Поле редактируется только в блоке логистики, чтобы не дублировать его в себестоимости.',
    formula: 'FBO channelVar += fbo_other',
  },
  fbs_last_mile: {
    label: 'Последняя миля FBS',
    unit: 'руб',
    section: 'Логистика',
    role: 'formula',
    tooltip: 'Логистика последней мили на одну продажу для FBS. Поддерживает весовой тариф и литровую формулу WB для marketplace delivery.',
    formula: 'boxDeliveryMarketplaceBase + boxDeliveryMarketplaceLiter * max(volumeLiters - 1, 0)',
  },
  fbs_ops: {
    label: 'Операции продавца FBS',
    unit: 'руб',
    section: 'Логистика',
    role: 'formula',
    tooltip: 'Операционные расходы продавца на обработку заказа FBS: сборка, передача, обработка на единицу.',
    formula: 'FBS channelVar += fbs_ops',
  },
  fbs_storage: {
    label: 'Хранение FBS',
    unit: 'руб',
    section: 'Логистика',
    role: 'formula',
    tooltip: 'Хранение на единицу для FBS. Учитывается только в FBS-канале.',
    formula: 'FBS channelVar += fbs_storage',
  },
  fbs_other: {
    label: 'Прочие переменные FBS',
    unit: 'руб',
    section: 'Логистика',
    role: 'formula',
    tooltip: 'Прочие переменные расходы на единицу для FBS. Поле редактируется только в блоке логистики, чтобы не дублировать его в себестоимости.',
    formula: 'FBS channelVar += fbs_other',
  },
  paid_share_pct: {
    label: 'Доля платного трафика',
    unit: '%',
    section: 'Маркетинг',
    role: 'formula',
    tooltip: 'Доля заказов, на которые приходится платный трафик. Умножается на CAC, чтобы получить маркетинговую стоимость на средний заказ.',
    formula: 'marketingCost = cac * paid_share_pct / 100',
  },
  cac: {
    label: 'CAC / платный заказ',
    unit: 'руб',
    section: 'Маркетинг',
    role: 'formula',
    tooltip: 'Стоимость привлечения одного платного заказа. В расчет contribution попадает только в доле платного трафика.',
    formula: 'marketingCost = cac * paid_share_pct / 100',
  },
  promo_pct: {
    label: 'Промо / акции',
    unit: '%',
    section: 'Маркетинг',
    role: 'formula',
    tooltip: 'Процент промо, скидок или акций от цены продажи. Вычитается из revenueNet как переменное удержание.',
    formula: 'promo = price * promo_pct / 100',
  },
  fixed_monthly: {
    label: 'Пост. расходы / мес.',
    unit: 'руб',
    section: 'Маркетинг',
    role: 'view',
    tooltip: 'Постоянные расходы в месяц. Не меняют прибыль на единицу, но участвуют в точке безубыточности и месячном прогнозе.',
    formula: 'bepUnits = fixedMonthlyTotal / contribution',
  },
  tax_system: {
    label: 'Система налогообложения',
    unit: '',
    section: 'Налоги и комиссии',
    role: 'formula',
    tooltip: 'Определяет налоговую базу. УСН Доходы считает налог от выручки без НДС; УСН Доходы-Расходы - от положительной разницы между выручкой и deductible расходами.',
    formula: 'taxBase зависит от tax_system',
  },
  tax_pct: {
    label: 'Ставка налога',
    unit: '%',
    section: 'Налоги и комиссии',
    role: 'formula',
    tooltip: 'Ставка налога для выбранной системы. Также используется в WB-отчете для расчета суммы налога по данным реализации.',
    formula: 'businessTax = taxBase * tax_pct / 100',
  },
  acquiring_pct: {
    label: 'Эквайринг',
    unit: '%',
    section: 'Налоги и комиссии',
    role: 'formula',
    tooltip: 'Процент эквайринга от цены продажи. Вычитается из revenueNet.',
    formula: 'acquiring = price * acquiring_pct / 100',
  },
  wb_commission_pct: {
    label: 'Комиссия WB',
    unit: '%',
    section: 'Налоги и комиссии',
    role: 'formula',
    tooltip: 'Комиссия Wildberries от цены продажи. Может подтягиваться из справочника комиссий по категории и схеме FBO/FBS.',
    formula: 'wbFee = price * wb_commission_pct / 100',
  },
  return_rate_pct: {
    label: 'Возвраты',
    unit: '%',
    section: 'Налоги и комиссии',
    role: 'formula',
    tooltip: 'Ожидаемая доля возвратов. Умножается на потерю на возврате и уменьшает gross profit.',
    formula: 'returnLossPerSale = return_rate_pct / 100 * return_loss',
  },
  return_loss: {
    label: 'Потеря на возврате',
    unit: 'руб',
    section: 'Налоги и комиссии',
    role: 'formula',
    tooltip: 'Средняя денежная потеря при одном возврате: обратная логистика, уценка, брак или обработка.',
    formula: 'returnLossPerSale = return_rate_pct / 100 * return_loss',
  },
  wb_sales_rub: {
    label: 'Продажи',
    unit: 'руб',
    section: 'WB отчет',
    role: 'report',
    tooltip: 'Сумма продаж из отчета WB до вычета возвратов. Используется только в блоке WB отчета.',
    formula: 'reportRevenue = wb_sales_rub - wb_returns_rub',
  },
  wb_returns_rub: {
    label: 'Возврат',
    unit: 'руб',
    section: 'WB отчет',
    role: 'report',
    tooltip: 'Сумма возвратов из отчета WB. Уменьшает выручку WB отчета, но не дублирует прогнозный процент возвратов в unit-экономике.',
    formula: 'reportRevenue = wb_sales_rub - wb_returns_rub',
  },
  wb_sales_units: {
    label: 'Итого продаж шт.',
    unit: 'шт',
    section: 'WB отчет',
    role: 'report',
    tooltip: 'Количество проданных единиц по отчету WB. Используется для средней цены, выкупа и прибыли на единицу.',
    formula: 'avgSalePrice = wb_sales_rub / wb_sales_units',
  },
  wb_cancellations_units: {
    label: 'Отмены и невыкупы',
    unit: 'шт',
    section: 'WB отчет',
    role: 'report',
    tooltip: 'Количество отмен и невыкупов из отчета. Используется для расчета процента выкупа.',
    formula: 'buyoutPct = salesUnits / (salesUnits + cancellationsUnits)',
  },
  wb_commission_rub: {
    label: 'Комиссия руб',
    unit: 'руб',
    section: 'WB отчет',
    role: 'report',
    tooltip: 'Фактическая комиссия WB в рублях из отчета. Не заменяет прогнозную комиссию в процентах.',
    formula: 'commissionPct = wb_commission_rub / reportRevenue',
  },
  wb_acquiring_rub: {
    label: 'Эквайринг руб',
    unit: 'руб',
    section: 'WB отчет',
    role: 'report',
    tooltip: 'Фактический эквайринг в рублях из отчета WB. Используется для доли эквайринга от отчетной выручки.',
    formula: 'acquiringPct = wb_acquiring_rub / reportRevenue',
  },
  wb_logistics_delivery_rub: {
    label: 'Логистика доставок',
    unit: 'руб',
    section: 'WB отчет',
    role: 'report',
    tooltip: 'Фактическая логистика доставок из отчета WB. Складывается с логистикой возвратов для отчетной доли логистики.',
    formula: 'totalLogistics = delivery + returnLogistics',
  },
  wb_logistics_return_rub: {
    label: 'Логистика возвратов',
    unit: 'руб',
    section: 'WB отчет',
    role: 'report',
    tooltip: 'Фактическая логистика возвратов из отчета WB. Не дублирует прогнозную потерю на возврате.',
    formula: 'totalLogistics = delivery + returnLogistics',
  },
  wb_payout_rub: {
    label: 'Оплата на Р/С',
    unit: 'руб',
    section: 'WB отчет',
    role: 'report',
    tooltip: 'Сумма выплаты на расчетный счет по отчету WB. Используется для фактической чистой прибыли отчета.',
    formula: 'netProfit = wb_payout_rub - taxAmount - wb_cogs_rub',
  },
  wb_cogs_rub: {
    label: 'Себестоимость',
    unit: 'руб',
    section: 'WB отчет',
    role: 'report',
    tooltip: 'Фактическая себестоимость проданных единиц для WB отчета. Отдельна от прогнозной себестоимости на единицу.',
    formula: 'netProfit = payout - taxAmount - wb_cogs_rub',
  },
  wb_realized_rub: {
    label: 'WB реализовал',
    unit: 'руб',
    section: 'WB отчет',
    role: 'report',
    tooltip: 'Налоговая база по реализации WB. Если не заполнена, отчетный расчет использует продажи.',
    formula: 'taxBase = wb_realized_rub || wb_sales_rub',
  },
  wb_total_net_profit_rub: {
    label: 'Чистая прибыль всего',
    unit: 'руб',
    section: 'WB отчет',
    role: 'report',
    tooltip: 'Итоговая чистая прибыль из отчета или внешней сверки. Используется для доли прибыли артикула относительно общего результата.',
    formula: 'profitSharePct = wb_total_net_profit_rub / netProfit',
  },
};

export const UNIT_ECONOMICS_FORMULA_FIELDS = [
  'fulfillment_mode',
  'price',
  'wb_commission_pct',
  'tax_system',
  'tax_pct',
  'acquiring_pct',
  'promo_pct',
  'return_rate_pct',
  'return_loss',
  'cogs_purchase',
  'cogs_packaging',
  'cogs_fulfillment',
  'cogs_inbound_to_wb',
  'waste_pct',
  'fbo_wb_logistics',
  'fbo_storage',
  'fbo_other',
  'fbs_last_mile',
  'fbs_ops',
  'fbs_storage',
  'fbs_other',
  'cac',
  'paid_share_pct',
  'fixed_monthly',
  'monthly_plan',
];

export const LOGISTICS_CONTEXT_FIELDS = [
  'package_mode',
  'size_length_cm',
  'size_width_cm',
  'size_height_cm',
  'weight_kg',
  'wb_boxes_per_pallet',
  'logistics_direction',
  'pickup_point',
];

export const WB_REPORT_INPUT_FIELDS = [
  'wb_sales_rub',
  'wb_returns_rub',
  'wb_sales_units',
  'wb_cancellations_units',
  'wb_commission_rub',
  'wb_acquiring_rub',
  'wb_logistics_delivery_rub',
  'wb_logistics_return_rub',
  'wb_payout_rub',
  'wb_cogs_rub',
  'wb_realized_rub',
  'wb_total_net_profit_rub',
];

export const REFERENCE_ONLY_FIELDS = [
  'wb_cabinet_price',
];

export const CALCULATOR_INPUT_PLACEMENTS = [
  { field: 'price', block: 'product-context' },
  { field: 'wb_cabinet_price', block: 'product-context' },
  { field: 'monthly_plan', block: 'product-context' },
  { field: 'size_length_cm', block: 'product-context' },
  { field: 'size_width_cm', block: 'product-context' },
  { field: 'size_height_cm', block: 'product-context' },
  { field: 'weight_kg', block: 'product-context' },
  { field: 'wb_boxes_per_pallet', block: 'product-context', mode: 'pallet' },
  { field: 'fulfillment_mode', block: 'product-context' },
  { field: 'package_mode', block: 'product-context' },
  { field: 'cogs_purchase', block: 'costs' },
  { field: 'cogs_packaging', block: 'costs' },
  { field: 'cogs_fulfillment', block: 'costs' },
  { field: 'cogs_inbound_to_wb', block: 'costs' },
  { field: 'waste_pct', block: 'costs' },
  { field: 'logistics_direction', block: 'logistics' },
  { field: 'pickup_point', block: 'logistics' },
  { field: 'fbo_wb_logistics', block: 'logistics', mode: 'FBO' },
  { field: 'fbo_storage', block: 'logistics', mode: 'FBO' },
  { field: 'fbo_other', block: 'logistics', mode: 'FBO' },
  { field: 'fbs_last_mile', block: 'logistics', mode: 'FBS' },
  { field: 'fbs_ops', block: 'logistics', mode: 'FBS' },
  { field: 'fbs_storage', block: 'logistics', mode: 'FBS' },
  { field: 'fbs_other', block: 'logistics', mode: 'FBS' },
  { field: 'paid_share_pct', block: 'marketing' },
  { field: 'cac', block: 'marketing' },
  { field: 'promo_pct', block: 'marketing' },
  { field: 'fixed_monthly', block: 'marketing' },
  { field: 'tax_system', block: 'taxes' },
  { field: 'tax_pct', block: 'taxes' },
  { field: 'acquiring_pct', block: 'taxes' },
  { field: 'wb_commission_pct', block: 'taxes' },
  { field: 'return_rate_pct', block: 'taxes' },
  { field: 'return_loss', block: 'taxes' },
  ...WB_REPORT_INPUT_FIELDS.map((field) => ({ field, block: 'wb-report' })),
];

export const CALCULATOR_PARAMETER_SECTIONS = [
  {
    title: 'Базовые параметры и габариты',
    fields: [
      'fulfillment_mode',
      'package_mode',
      'price',
      'wb_cabinet_price',
      'monthly_plan',
      'size_length_cm',
      'size_width_cm',
      'size_height_cm',
      'weight_kg',
      'wb_boxes_per_pallet',
    ],
  },
  {
    title: 'Себестоимость',
    fields: ['cogs_purchase', 'cogs_packaging', 'cogs_fulfillment', 'cogs_inbound_to_wb', 'waste_pct'],
  },
  {
    title: 'Логистика',
    fields: [
      'logistics_direction',
      'pickup_point',
      'fbo_wb_logistics',
      'fbo_storage',
      'fbo_other',
      'fbs_last_mile',
      'fbs_ops',
      'fbs_storage',
      'fbs_other',
    ],
  },
  {
    title: 'Маркетинг',
    fields: ['paid_share_pct', 'cac', 'promo_pct', 'fixed_monthly'],
  },
  {
    title: 'Налоги и комиссии',
    fields: ['tax_system', 'tax_pct', 'acquiring_pct', 'wb_commission_pct', 'return_rate_pct', 'return_loss'],
  },
  {
    title: 'WB отчет',
    fields: WB_REPORT_INPUT_FIELDS,
  },
];

export function getCalculatorParameterDoc(field) {
  return CALCULATOR_PARAMETER_DOCS[field] || {
    label: field,
    unit: '',
    section: 'Калькулятор',
    role: 'unknown',
    tooltip: 'Параметр калькулятора.',
    formula: '',
  };
}
